#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: org.ckj.ssm.mybatis.entity
  # 应用服务 WEB 访问端口
server:
  port: 8090

spring:
  datasource:
    host: localhost
    port: 3306
    database: mysql_demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?serverTimezone=GMT%2b8
    username: root
    password: 123456