# 应用服务 WEB 访问端口
server:
  port: 8092
  #下面这些内容是为了让MyBatis映射
  #指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: org.ckj.springredis.mybatis.entity

spring:
  datasource:
    host: localhost
    port: 3306
    username: root
    password: 123456
    database: mysql_demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
    port: 6379
    database: 0
